version: "3.7"

services:
  php:
    platform: linux/amd64
    restart: unless-stopped
    container_name: test-service
    build:
      dockerfile: ./docker/php.Dockerfile
    ports:
      - 8000:8000
    #для ubuntu 20.04 https://bugzilla.redhat.com/show_bug.cgi?id=1990469#c9
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./:/var/www:delegated
    working_dir: /var/www/
    networks:
      - test-service-network

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - test-service-network
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
  test-service-network:
    name: test-service-network
    driver: bridge
    ipam:
      driver: default
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
