controllers:
    resource:
        path: ../../src/ProductApi/Controller
        namespace: App\ProductApi\Controller
    type: attribute
    prefix: /v1

when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
